[[redirects]]
  from = "/crm"
  to = "/crm/login.html"
  status = 200

[[redirects]]
  from = "/crm/"
  to = "/crm/index.html"
  status = 200

[[redirects]]
  from = "/crm/*"
  to = "/crm/:splat"
  status = 200

[build]
  publish = "."
  command = "echo 'No build required'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/crm/*"
  [headers.values]
    Cache-Control = "no-cache"
